# Generated by Django 4.1.5 on 2023-01-24 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NayveeBasyes',
            fields=[
                ('id_base_de_dado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('historia', models.CharField(max_length=250)),
                ('divida', models.CharField(max_length=250)),
                ('garantias', models.CharField(max_length=250)),
                ('renda', models.CharField(max_length=250)),
            ],
        ),
    ]
